import type {
  CoreWorkDef,
  Handover,
  ScheduleRow,
  ShiftDef,
  Team,
  User,
  WorkItem,
} from "@/types";

export const currentUser: User = {
  id: "u-op-a",
  name: "Operator A",
  initials: "OA",
  role: "member",
  teamId: "t-prod-a",
  shift: "Shift 1 · 07:00 - 15:00",
};

export const users: User[] = [
  currentUser,
  { id: "u-sup-a", name: "Supervisor A", initials: "SA", role: "leader", teamId: "t-prod-a" },
  { id: "u-op-b", name: "Operator B", initials: "OB", role: "member", teamId: "t-prod-a" },
  { id: "u-op-c", name: "Operator C", initials: "OC", role: "member", teamId: "t-prod-a" },
  { id: "u-op-1", name: "Operator 1", initials: "O1", role: "member", teamId: "t-prod-a" },
  { id: "u-op-2", name: "Operator 2", initials: "O2", role: "member", teamId: "t-prod-a" },
];

export const userByName = (name: string): User | undefined =>
  users.find((u) => u.name === name);

export const teams: Team[] = [
  { id: "t-prod-a", name: "Production Team A", leaderId: "u-sup-a", memberIds: ["u-op-a", "u-op-b", "u-op-c", "u-op-1", "u-op-2"], active: true, coreWorkCount: 4 },
  { id: "t-maint", name: "Maintenance", leaderId: "u-sup-a", memberIds: ["u-op-c"], active: true, coreWorkCount: 2 },
  { id: "t-qc", name: "Quality Control", leaderId: "u-sup-a", memberIds: ["u-op-1"], active: false, coreWorkCount: 1 },
];

export const shifts: ShiftDef[] = [
  { id: "s1", name: "Shift 1", code: "S1", start: "07:00", end: "15:00" },
  { id: "s2", name: "Shift 2", code: "S2", start: "15:00", end: "23:00" },
  { id: "s3", name: "Shift 3", code: "S3", start: "23:00", end: "07:00" },
];

export const works: WorkItem[] = [
  {
    id: "w-1",
    number: "TK-000125",
    title: "Check Machine Line 4",
    type: "adhoc",
    status: "in_progress",
    priority: "high",
    createdBy: "Supervisor A",
    assignedTo: "Operator A",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "26 Sep 2026",
    description: "Check machine condition and record findings. Pastikan tekanan, suhu, dan vibrasi tercatat.",
    progress: 70,
    evidenceRequired: true,
    evidences: [
      { id: "e1", fileName: "photo-001.jpg", fileType: "image/jpeg", fileSize: "2.4 MB", uploadedBy: "Operator A", uploadedAt: "26 Sep 2026 09:10" },
      { id: "e2", fileName: "photo-002.jpg", fileType: "image/jpeg", fileSize: "1.8 MB", uploadedBy: "Operator A", uploadedAt: "26 Sep 2026 10:42" },
    ],
    checklist: [
      { id: "c1", label: "Oil", done: true },
      { id: "c2", label: "Temperature", done: true },
      { id: "c3", label: "Pressure", done: false },
    ],
    note: "Machine pressure still needs checking.",
    createdAt: "26 Sep 2026 07:05",
    updatedAt: "26 Sep 2026 10:42",
    activities: [
      { id: "a1", at: "26 Sep 2026 07:10", text: "started task", actor: "Operator A" },
      { id: "a2", at: "26 Sep 2026 08:30", text: "Progress changed from 20% to 50%", actor: "Operator A" },
      { id: "a3", at: "26 Sep 2026 09:10", text: "Evidence uploaded (photo-001.jpg)", actor: "Operator A" },
    ],
  },
  {
    id: "w-2",
    number: "CW-2026-031",
    title: "Machine Daily Inspection",
    type: "core",
    status: "completed",
    priority: "medium",
    createdBy: "System",
    assignedTo: "Operator A",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "26 Sep 2026",
    description: "Rutin harian: cek oil, temperature, pressure, vibration semua line.",
    progress: 100,
    evidenceRequired: true,
    evidences: [
      { id: "e3", fileName: "inspection.jpg", fileType: "image/jpeg", fileSize: "3.1 MB", uploadedBy: "Operator A", uploadedAt: "26 Sep 2026 08:00" },
    ],
    checklist: [
      { id: "c1", label: "Check oil", done: true },
      { id: "c2", label: "Check temperature", done: true },
      { id: "c3", label: "Check pressure", done: true },
      { id: "c4", label: "Check vibration", done: true },
    ],
    note: "Semua normal.",
    createdAt: "26 Sep 2026 07:00",
    updatedAt: "26 Sep 2026 08:15",
    activities: [
      { id: "a1", at: "26 Sep 2026 07:12", text: "started task", actor: "Operator A" },
      { id: "a2", at: "26 Sep 2026 08:15", text: "completed by Operator A", actor: "Operator A" },
    ],
  },
  {
    id: "w-3",
    number: "CW-2026-032",
    title: "Temperature Check",
    type: "core",
    status: "in_progress",
    priority: "medium",
    createdBy: "System",
    assignedTo: "Operator A",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "26 Sep 2026",
    description: "Cek suhu tiap 2 jam dan catat.",
    progress: 50,
    evidenceRequired: false,
    evidences: [],
    checklist: [
      { id: "c1", label: "Line 1-3", done: true },
      { id: "c2", label: "Line 4-5", done: false },
    ],
    note: "Inspection machine 1–3 completed. Machine 4 masih dalam pengecekan.",
    createdAt: "26 Sep 2026 07:00",
    updatedAt: "26 Sep 2026 09:30",
    activities: [
      { id: "a1", at: "26 Sep 2026 08:30", text: "Progress changed from 20% to 50%", actor: "Operator A" },
    ],
  },
  {
    id: "w-4",
    number: "TK-000126",
    title: "Cleaning Area 2",
    type: "adhoc",
    status: "handover",
    priority: "low",
    createdBy: "Supervisor A",
    assignedTo: "Operator A",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "26 Sep 2026",
    description: "Cleaning area 2 sebelum handover.",
    progress: 60,
    evidenceRequired: false,
    evidences: [],
    checklist: [],
    note: "Sisa area belakang belum sempat.",
    createdAt: "26 Sep 2026 10:00",
    updatedAt: "26 Sep 2026 14:45",
    activities: [
      { id: "a1", at: "26 Sep 2026 14:45", text: "handed over to Operator B", actor: "Operator A" },
    ],
  },
  {
    id: "w-5",
    number: "TK-000127",
    title: "Repair Area B",
    type: "adhoc",
    status: "todo",
    priority: "high",
    createdBy: "Supervisor A",
    assignedTo: "Operator B",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 2",
    dueDate: "26 Sep 2026",
    description: "Perbaiki conveyor area B.",
    progress: 0,
    evidenceRequired: true,
    evidences: [],
    checklist: [],
    note: "",
    createdAt: "26 Sep 2026 11:00",
    updatedAt: "26 Sep 2026 11:00",
    activities: [],
  },
  {
    id: "w-6",
    number: "TK-000124",
    title: "Verify stock discrepancy",
    type: "adhoc",
    status: "completed",
    priority: "medium",
    createdBy: "Supervisor A",
    assignedTo: "Operator C",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "25 Sep 2026",
    description: "Verifikasi selisih stok.",
    progress: 100,
    evidenceRequired: false,
    evidences: [],
    checklist: [],
    note: "",
    createdAt: "25 Sep 2026 09:00",
    updatedAt: "25 Sep 2026 16:00",
    activities: [
      { id: "a1", at: "25 Sep 2026 16:00", text: "completed by Operator C", actor: "Operator C" },
    ],
  },
  {
    id: "w-7",
    number: "TK-000128",
    title: "Clean specific equipment",
    type: "adhoc",
    status: "todo",
    priority: "low",
    createdBy: "Supervisor A",
    assignedTo: "Operator A",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "26 Sep 2026",
    description: "Dibatalkan: equipment sudah dibersihkan vendor.",
    progress: 0,
    evidenceRequired: false,
    cancelled: true,
    evidences: [],
    checklist: [],
    note: "",
    createdAt: "26 Sep 2026 08:00",
    updatedAt: "26 Sep 2026 12:00",
    activities: [
      { id: "a1", at: "26 Sep 2026 12:00", text: "cancelled by Supervisor A", actor: "Supervisor A" },
    ],
  },
  {
    id: "w-8",
    number: "TK-000129",
    title: "Calibrate sensor line 1",
    type: "adhoc",
    status: "todo",
    priority: "medium",
    createdBy: "Supervisor A",
    assignedTo: "Operator B",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 2",
    dueDate: "27 Sep 2026",
    description: "Kalibrasi sensor dan catat hasil.",
    progress: 0,
    evidenceRequired: true,
    evidences: [],
    checklist: [],
    note: "",
    createdAt: "26 Sep 2026 11:30",
    updatedAt: "26 Sep 2026 11:30",
    activities: [],
  },
  {
    id: "w-9",
    number: "CW-2026-033",
    title: "Area Cleaning",
    type: "core",
    status: "in_progress",
    priority: "low",
    createdBy: "System",
    assignedTo: "Operator A",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "26 Sep 2026",
    description: "Cleaning area kerja sebelum akhir shift.",
    progress: 30,
    evidenceRequired: false,
    evidences: [],
    checklist: [
      { id: "c1", label: "Area 1", done: true },
      { id: "c2", label: "Area 2", done: false },
    ],
    note: "",
    createdAt: "26 Sep 2026 07:00",
    updatedAt: "26 Sep 2026 13:00",
    activities: [
      { id: "a1", at: "26 Sep 2026 13:00", text: "Progress changed from 0% to 30%", actor: "Operator A" },
    ],
  },
  {
    id: "w-10",
    number: "CW-2026-034",
    title: "End Shift Report",
    type: "core",
    status: "handover",
    priority: "medium",
    createdBy: "System",
    assignedTo: "Operator A",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "26 Sep 2026",
    description: "Laporan akhir shift beserta pending work.",
    progress: 80,
    evidenceRequired: true,
    evidences: [],
    checklist: [
      { id: "c1", label: "Summary", done: true },
      { id: "c2", label: "Pending work", done: false },
    ],
    note: "Pending work belum lengkap.",
    createdAt: "26 Sep 2026 07:00",
    updatedAt: "26 Sep 2026 14:30",
    activities: [
      { id: "a1", at: "26 Sep 2026 14:30", text: "handed over to Operator B", actor: "Operator A" },
    ],
  },
  {
    id: "w-11",
    number: "TK-000123",
    title: "Lubricate conveyor",
    type: "adhoc",
    status: "completed",
    priority: "low",
    createdBy: "Supervisor A",
    assignedTo: "Operator B",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 2",
    dueDate: "25 Sep 2026",
    description: "Lubrikasi conveyor line 3.",
    progress: 100,
    evidenceRequired: false,
    evidences: [],
    checklist: [],
    note: "",
    createdAt: "25 Sep 2026 10:00",
    updatedAt: "25 Sep 2026 14:00",
    activities: [
      { id: "a1", at: "25 Sep 2026 14:00", text: "completed by Operator B", actor: "Operator B" },
    ],
  },
  {
    id: "w-12",
    number: "TK-000130",
    title: "Verify packaging seal",
    type: "adhoc",
    status: "in_progress",
    priority: "high",
    createdBy: "Supervisor A",
    assignedTo: "Operator C",
    team: "Production A",
    teamId: "t-prod-a",
    shift: "Shift 1",
    dueDate: "26 Sep 2026",
    description: "Verifikasi seal packaging batch pagi.",
    progress: 45,
    evidenceRequired: true,
    evidences: [],
    checklist: [],
    note: "",
    createdAt: "26 Sep 2026 09:00",
    updatedAt: "26 Sep 2026 12:30",
    activities: [
      { id: "a1", at: "26 Sep 2026 12:30", text: "Progress changed from 10% to 45%", actor: "Operator C" },
    ],
  },
];

export const coreWorks: CoreWorkDef[] = [
  { id: "cw-1", name: "Machine Daily Inspection", description: "Inspeksi harian semua line produksi", team: "Production A", frequency: "Daily / Shift 1", schedule: "S1 · 07:00", evidenceRequired: true, checklist: ["Check oil", "Check temperature", "Check pressure", "Check vibration"], status: "active", todayInstance: "CW-2026-031" },
  { id: "cw-2", name: "Temperature Check", description: "Cek suhu tiap 2 jam", team: "Production A", frequency: "Every 2 hours", schedule: "All shifts", evidenceRequired: false, checklist: ["Line 1-3", "Line 4-5"], status: "active", todayInstance: "CW-2026-032" },
  { id: "cw-3", name: "Area Cleaning", description: "Cleaning area kerja", team: "Production A", frequency: "Daily", schedule: "End of shift", evidenceRequired: false, checklist: ["Area 1", "Area 2"], status: "active" },
  { id: "cw-4", name: "End Shift Report", description: "Laporan akhir shift", team: "Production A", frequency: "Per shift", schedule: "30 mnt sebelum shift end", evidenceRequired: true, checklist: ["Summary", "Pending work"], status: "active" },
  { id: "cw-5", name: "Weekly Calibration", description: "Kalibrasi mingguan", team: "Maintenance", frequency: "Weekly", schedule: "Monday S1", evidenceRequired: true, checklist: ["Calibrate", "Record"], status: "inactive" },
];

export const handovers: Handover[] = [
  { id: "h-1", taskNumber: "TK-000126", taskTitle: "Cleaning Area 2", from: "Operator A", fromShift: "Shift 1", to: "Operator B", toShift: "Shift 2", progress: 60, note: "Machine 4 masih menunggu maintenance confirmation. Sisa area belakang.", status: "pending", handoverAt: "26 Sep 2026 14:45" },
  { id: "h-2", taskNumber: "TK-000120", taskTitle: "Check Machine Line 2", from: "Operator C", fromShift: "Shift 3", to: "Operator A", toShift: "Shift 1", progress: 70, note: "Tinggal final check.", status: "accepted", handoverAt: "26 Sep 2026 06:50", acceptedAt: "26 Sep 2026 07:05" },
];

export const scheduleRows: ScheduleRow[] = [
  { user: "Operator A", userId: "u-op-a", days: { Mon: "S1", Tue: "S1", Wed: "S2", Thu: "S2", Fri: "S1", Sat: "OFF", Sun: "OFF" } },
  { user: "Operator B", userId: "u-op-b", days: { Mon: "S2", Tue: "S2", Wed: "S1", Thu: "S1", Fri: "S2", Sat: "OFF", Sun: "OFF" } },
  { user: "Operator C", userId: "u-op-c", days: { Mon: "OFF", Tue: "S1", Wed: "S1", Thu: "S2", Fri: "S2", Sat: "S1", Sun: "S1" } },
];

export const dashboardStats = {
  open: 8,
  inProgress: 5,
  pendingHandover: 2,
  completedToday: 12,
  overdue: 1,
  currentShift: "Shift 1 · 07:00 - 15:00",
};
